#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

files=$(git diff --cached --name-only)
yarn cspell --no-summary --no-must-find-files $files
npx pretty-quick --staged